### ISSUE TITLE
Cannot run correctly

### ISSUE THREAD

**Issue by hyichao** [Baekalfen/PyBoy#132]
Hi,

I've read the documentation and then try to install and run but failed. Here's what I've done.

1. download from this [link](https://www.downloadroms.io/roms/gameboy-advance/) and named `pokemon.gba`
2. `sudo apt install libsdl2-dev`
3. `pip install pyboy`
4. `pyboy pokemon.gba`

And I got the following

```
350      pyboy.__main__                 INFO     
The Game Boy controls are as follows:

| Keyboard key | GameBoy equivalant |
| ---          | ---                |
| Up           | Up                 |
| Down         | Down               |
| Left         | Left               |
| Right        | Right              |
| A            | A                  |
| S            | B                  |
| Return       | Start              |
| Backspace    | Select             |

The other controls for the emulator:

| Keyboard key | Emulator function       |
| ---          | ---                     |
| Escape       | Quit                    |
| D            | Debug                   |
| Space        | Unlimited FPS           |
| Z            | Save state              |
| X            | Load state              |
| I            | Toggle screen recording |
| ,            | Rewind backwards        |
| .            | Rewind forward          |

See "pyboy --help" for how to enable rewind and other awesome features!

Traceback (most recent call last):
  File "/home/charlie/venv3/bin/pyboy", line 8, in <module>
    sys.exit(main())
  File "/home/charlie/venv3/lib/python3.6/site-packages/pyboy/__main__.py", line 122, in main
    pyboy = PyBoy(argv.ROM, **vars(argv))
  File "pyboy/pyboy.py", line 64, in pyboy.pyboy.PyBoy.__init__
  File "pyboy/core/mb.py", line 28, in pyboy.core.mb.Motherboard.__init__
  File "pyboy/core/cartridge/cartridge.py", line 24, in pyboy.core.cartridge.cartridge.load_cartridge
  File "pyboy/core/cartridge/cartridge.py", line 27, in pyboy.core.cartridge.cartridge.load_cartridge
Exception: Cartridge header checksum mismatch!
```
Any help?

**Comment by Baekalfen** [comment]
It looks like you're trying to load a Game Boy Advance game. This project only emulates the original Game Boy
