### ISSUE TITLE
SyntaxError: invalid syntax when $ pip install pyboy

### ISSUE THREAD

**Issue by taco-chen** [Baekalfen/PyBoy#198]
I met the following syntax error message when I tried to install the PyBoy.

```
$ pip install pyboy
Downloading/unpacking pyboy
  Downloading pyboy-1.4.1.tar.gz (6.0MB): 6.0MB downloaded
  Running setup.py (path:/private/var/folders/b_/j16ngfyd2k5dmq8y5mb8ls200000gn/T/pip_build_xxx/pyboy/setup.py) egg_info for package pyboy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/private/var/folders/b_/j16ngfyd2k5dmq8y5mb8ls200000gn/T/pip_build_xxx/pyboy/setup.py", line 80
        f"DEF DEBUG={int(bool(DEBUG))}\n",
                                        ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/private/var/folders/b_/j16ngfyd2k5dmq8y5mb8ls200000gn/T/pip_build_xxx/pyboy/setup.py", line 80

    f"DEF DEBUG={int(bool(DEBUG))}\n",

                                    ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /private/var/folders/b_/j16ngfyd2k5dmq8y5mb8ls200000gn/T/pip_build_taco/pyboy
Storing debug log for failure in /Users/taco/Library/Logs/pip.log
```

**Comment by krs013** [comment]
What are your system details? Any chance you accidentally used Python 2 and not Python 3?

**Comment by taco-chen** [comment]
Yeah, sorry. It seems my stupid mistake. The installation run perfectly with Python3. Thanks 💯
